export class Constants {
  static readonly SWIPER_DEFAULT_WIDTH: string = '66%';
  static readonly FULL_PERCENT: string = '100%';
  static readonly HALF_PERCENT: string = '50%';
  static readonly IMAGE_CONTAINER_HEIGHT: string = '42%';
  static readonly FULL_SIZE: string = '100%';
  static readonly ICON_SIZE: string = '40%';
  static readonly BAR_WEIGHT: string = '25%';
  static readonly BAR_HEIGHT: string = '10%';
  static readonly CONTENT_WIDTH_PERCENT: string = '87%';
  static readonly SEARCHBAR_WIDTH: string = '91.1%'
  static readonly IMAGE_HEIGHT_MIN: string = '78%';

  //TabItem
  static readonly HOME_TITLE: string = '首页';
  static readonly SQUARE_TITLE: string = '广场';
  static readonly ME_TITLE: string = "我的";

  /**
   * Component constants.
   */
  static readonly OPACITY: number = 0.6;
  static readonly BORDER_WIDTH: number = 0.5;
  static readonly COUNTDOWN: number = 5;

  //圆角的RADIUS
  static readonly BORDER_RADIUS = 12;
  //tab页的宽
  static readonly PAGE_WIDTH = '94.4%';
  //banner的高
  static readonly HEIGHT_BANNER = '27%';
  //动画执行的时间.
  static readonly DURATION_ADS = 200;
  //滚动持续时间
  static readonly SWIPER_TIME = 1500;
}